<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Engine</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Include="Shaders\*.vs" />
      <EmbeddedResource Include="Shaders\*.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Raylib-cs" Version="8.0.0" />
    </ItemGroup>

</Project>
